import { jsPDF } from "jspdf";

type WorkflowReportInput = {
  companyName: string;
  workflowName: string;
  referenceNumber: string;
  status: string;
  startedAt: string;
  closedAt: string | null;
  data: Record<string, unknown>;
  tasks: Array<{ stage_key: string; status: string; decision?: string | null; comment?: string | null; completed_at?: string | null }>;
};

export function buildWorkflowReport(input: WorkflowReportInput) {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  const width = 499;
  let y = 52;

  const write = (text: string, size = 10, color: [number, number, number] = [54, 65, 78]) => {
    pdf.setFontSize(size);
    pdf.setTextColor(...color);
    const lines = pdf.splitTextToSize(text, width);
    pdf.text(lines, margin, y);
    y += lines.length * (size + 4);
  };
  const ensurePage = (needed = 60) => {
    if (y + needed > 790) { pdf.addPage(); y = 52; }
  };

  pdf.setFillColor(49, 94, 203);
  pdf.rect(0, 0, 595, 12, "F");
  write("WORKGRID · FINAL WORKFLOW REPORT", 9, [72, 100, 160]);
  y += 8;
  write(input.workflowName, 22, [24, 33, 43]);
  write(`${input.companyName}  ·  ${input.referenceNumber}`, 10, [105, 118, 132]);
  y += 12;

  pdf.setDrawColor(225, 229, 234);
  pdf.line(margin, y, margin + width, y);
  y += 24;
  write(`Status: ${input.status.toUpperCase()}`, 11, [49, 94, 203]);
  write(`Started: ${new Date(input.startedAt).toLocaleString("en-GB")}`);
  write(`Closed: ${input.closedAt ? new Date(input.closedAt).toLocaleString("en-GB") : "Not recorded"}`);
  y += 18;

  write("SUBMITTED DATA", 10, [72, 100, 160]);
  y += 5;
  for (const [key, value] of Object.entries(input.data)) {
    ensurePage();
    write(`${key.replaceAll("_", " ")}: ${typeof value === "object" ? JSON.stringify(value) : String(value)}`);
  }
  if (!Object.keys(input.data).length) write("No submitted fields were recorded.", 10, [120, 132, 145]);

  y += 18;
  ensurePage(90);
  write("APPROVAL HISTORY", 10, [72, 100, 160]);
  y += 5;
  for (const task of input.tasks) {
    ensurePage(70);
    write(`${task.stage_key.replaceAll("_", " ")} — ${task.status}`, 11, [38, 48, 60]);
    if (task.decision) write(`Decision: ${task.decision}`, 9);
    if (task.comment) write(`Comment: ${task.comment}`, 9);
    if (task.completed_at) write(`Completed: ${new Date(task.completed_at).toLocaleString("en-GB")}`, 9, [120, 132, 145]);
    y += 8;
  }
  if (!input.tasks.length) write("No approval tasks were recorded.", 10, [120, 132, 145]);

  const pages = pdf.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    pdf.setPage(page);
    pdf.setFontSize(8);
    pdf.setTextColor(145, 155, 166);
    pdf.text(`Generated by WorkGrid · Page ${page} of ${pages}`, margin, 812);
  }

  return Buffer.from(pdf.output("arraybuffer"));
}
